# =========================================================
# APPLICATION
# =========================================================
spring.application.name=BE

# =========================================================
# SERVER
# =========================================================
server.port=${PORT:8080}

# =========================================================
# DATABASE CONFIG
# =========================================================
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =========================================================
# HIKARI CONNECTION POOL
# =========================================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

# =========================================================
# LOGGING
# =========================================================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=OFF

# =========================================================
# CLOUDINARY
# =========================================================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# =========================================================
# JACKSON
# =========================================================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# =========================================================
# FILE UPLOAD
# =========================================================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# =========================================================
# UTF-8
# =========================================================
spring.messages.encoding=UTF-8

# =========================================================
# VNPAY
# =========================================================
vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.hash-secret=${VNPAY_HASH_SECRET}
vnpay.pay-url=${VNPAY_PAY_URL}
vnpay.return-url=${VNPAY_RETURN_URL}
vnpay.ipn-url=${VNPAY_IPN_URL}

# AI service
ai.service.url=https://vsignai-ai-lb84m.ondigitalocean.app/predict

#ai.service.url=https://v-signai-ai.onrender.com